version: 2

jobs:
   build:
     machine:
       node:
         version: 6.9.5
       npm:
         version: 3.10.10
     steps:
       - checkout
       - run: npm install -g npm@latest
       - restore_cache:
           key: dependency-cache-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
           paths:
             - ./node_modules
       - run: npm test
       - store_artifacts:
          path: .nyc_output
       - store_test_results:
          path: test-results.json
